name: BUILD

on:
  push:
    paths:
      - 'deploy/docker/**'
      - 'library'
      - 'Makefile'
      - '.github/workflows/build_image.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Log in to the Container registry 🚪
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker 🏋️
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/ros_complete_env
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image 🏗️
        uses: docker/build-push-action@v4
        with:
          file: deploy/docker/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: basic

  build-python-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Python3 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install follow_the_drow Python library locally 👇
        run: make venv

  build-cpp-static-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up GCC 🛠️
        uses: egor-tensin/setup-gcc@v1
        with:
          version: '11'

      - name: Build and install follow_the_drow C++ static library 📚
        run: sudo make build-lib

  build-ftd-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Build image 🖼️
        run: make build-image
